default_language_version:
  python: python3.10

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-toml
  - id: check-case-conflict
  - id: check-merge-conflict

- repo: https://github.com/asottile/pyupgrade
  rev: v3.9.0
  hooks:
  - id: pyupgrade
    args: [--py37-plus]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black

- repo: https://github.com/asottile/blacken-docs
  rev: 1.15.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==22.6.0

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-tidy-imports
    - flake8-typing-imports

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.4.1
  hooks:
  - id: mypy
    files: ^redis_search_django/
    additional_dependencies: [types-redis]
